import { afterEach, describe, expect, it, vi } from "vitest";
import { clearControlPlaneForTests, configureControlPlane, request, subscribeSessionEvents } from "./api";

afterEach(()=>{vi.unstubAllGlobals();clearControlPlaneForTests()});
describe("HTTP control-plane client",()=>{
 it("adds bearer auth without putting token in URL",async()=>{configureControlPlane({baseUrl:"http://127.0.0.1:5100/",token:"top-secret"});const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({ok:true}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);await request("/v1/version");const [url,init]=fetchMock.mock.calls[0];expect(url).toBe("http://127.0.0.1:5100/v1/version");expect(url).not.toContain("top-secret");expect(new Headers(init.headers).get("Authorization")).toBe("Bearer top-secret")});
 it("normalizes API errors",async()=>{configureControlPlane({baseUrl:"http://local",token:"x"});vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({detail:"profile not found"}),{status:404,headers:{"Content-Type":"application/json"}})));await expect(request("/v1/profiles/9")).rejects.toEqual(expect.objectContaining({status:404,code:"HTTP_404",message:"profile not found"}))});
 it("returns an unavailable error on transport failure",async()=>{configureControlPlane({baseUrl:"http://local",token:"x"});vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new TypeError("secret details")));await expect(request("/v1/profiles")).rejects.toEqual(expect.objectContaining({code:"CONTROL_PLANE_UNAVAILABLE"}))});
 it("SSE uses auth and can be cancelled",async()=>{configureControlPlane({baseUrl:"http://local",token:"secret"});const stream=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('id: 2\r\nevent: session.ready\r\ndata: {"data":{"status":"ready"}}\r\n\r\n'));}});const f=vi.fn().mockResolvedValue(new Response(stream,{status:200}));vi.stubGlobal("fetch",f);const event=await new Promise<{sequence:number}>(resolve=>{const close=subscribeSessionEvents("sid",e=>{close();resolve(e)});});expect(event.sequence).toBe(2);expect(new Headers(f.mock.calls[0][1].headers).get("Authorization")).toBe("Bearer secret")});
 it("SSE reconnects with Last-Event-ID and survives malformed events",async()=>{vi.useFakeTimers();configureControlPlane({baseUrl:"http://local",token:"secret"});const first=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('id: 7\ndata: {"type":"tick"}\n\ndata: not-json\n\n'));c.close()}});const second=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('id: 8\ndata: {"type":"done"}\n\n'));}});const f=vi.fn().mockResolvedValueOnce(new Response(first,{status:200})).mockResolvedValueOnce(new Response(second,{status:200}));vi.stubGlobal("fetch",f);let close=()=>{};const done=new Promise<void>(resolve=>{close=subscribeSessionEvents("sid",e=>{if(e.sequence===8){close();resolve()}})});await vi.advanceTimersByTimeAsync(500);await done;expect(new Headers(f.mock.calls[1][1].headers).get("Last-Event-ID")).toBe("7");vi.useRealTimers()});
});
